### PR TITLE
Add auto completion to the pyconsole

### PR DESCRIPTION
**Pull request by MaximilienNaveau**
In this pull request I modified the py_console for several purpose:
1/ Kinetic compatibility. On Ubuntu 16.04 ros is using pyqt5 and spider pyqt4 which are not compatible.
Hence we loose all the work from Andrea about the auto-completion and the setup.
Therefore I update the py_console so we can use it on Ubuntu16.04 (ros:Kinetic) and have an auto-completion with it.
2/ Compatibility between using the dynamic_graph_manager (MPI-Tubingen dynamic graph bridge) and the dynamic_graph_bridge_msg (From LAAS). We use slitghtly different service names in the two packages so I made sure the client can pick the one available.

It would be very nice if one the people in LAAS could test the pyconsole on the DynamicGraphBridge in LAAS to make sure that the compatibility hold.

Thank you very much.

### CODE REVIEW

**Comment by olivier-stasse** [comment]
Hi Max,
I got the following error:
```
rosrun rqt_gui rqt_gui 
RosPluginProvider.load(rqt_dynamic_graph/PyConsole) exception raised in __builtin__.__import__(rqt_dynamic_graph.py_console, [PyConsole]):
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 80, in load
    module = __builtin__.__import__(attributes['module_name'], fromlist=[attributes['class_from_class_type']], level=0)
  File "/opt/openrobots/lib/python2.7/site-packages/rqt_dynamic_graph/py_console.py", line 33, in <module>
    from python_qt_binding.QtGui import QVBoxLayout, QWidget
ImportError: cannot import name QVBoxLayout

PluginManager._load_plugin() could not load plugin "rqt_dynamic_graph/PyConsole":
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/plugin_handler.py", line 99, in load
    self._load()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py", line 54, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 86, in load
    raise e
ImportError: cannot import name QVBoxLayout
```
Any idea ?

**Comment by MaximilienNaveau** [comment]
Yes I have a hint. My guess is that in the transition between ubuntu14.04 and ubuntu16.04 and higher, the version of pyqt used by ros is different.

My solution would be to impose the use of one version of pyqt.
For example pyqt4 would be a good choice as it easily installable in all ubuntu version from 14.04 to higher.

What do you think?

**Comment by olivier-stasse** [comment]
On 16.04 in a bizarre way it is pyqt5 for python 2.7 and pyqt4 for python3.
So I guess this is fine.

**Comment by olivier-stasse** [comment]
My bad there is also pyqt5 for python3

**Pull request merged**
